-- Initial schema, created by Flyway and validated by Hibernate

CREATE TABLE lecturer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    surname     VARCHAR(255) NOT NULL,
    CONSTRAINT uk_lecturer_lecturer_id UNIQUE (lecturer_id)
);

CREATE TABLE student
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(255) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    surname    VARCHAR(255) NOT NULL,
    CONSTRAINT uk_student_student_id UNIQUE (student_id)
);

CREATE TABLE assignment
(
    lecturer_id BIGINT NOT NULL,
    student_id  BIGINT NOT NULL,
    PRIMARY KEY (lecturer_id, student_id),
    CONSTRAINT fk_assignment_lecturer FOREIGN KEY (lecturer_id) REFERENCES lecturer (id),
    CONSTRAINT fk_assignment_student FOREIGN KEY (student_id) REFERENCES student (id)
);