-- Initial schema, applied by Flyway on startup; Hibernate runs in `validate` mode against it.

-- Lecturers. One row per lecturer.
CREATE TABLE lecturer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- surrogate PK; DB-generated, never exposed to clients
    lecturer_id VARCHAR(255) NOT NULL,                               -- business id supplied by the API; the public handle
    name        VARCHAR(255) NOT NULL,                               -- given name; required
    surname     VARCHAR(255) NOT NULL,                               -- family name; required
    CONSTRAINT uk_lecturer_lecturer_id UNIQUE (lecturer_id)          -- enforces "create lecturer fails if it already exists"
);

-- Students. One row per student.
CREATE TABLE student
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- surrogate PK; DB-generated, never exposed to clients
    student_id VARCHAR(255) NOT NULL,                               -- business id supplied by the API; the public handle
    name       VARCHAR(255) NOT NULL,                               -- given name; required
    surname    VARCHAR(255) NOT NULL,                               -- family name; required
    CONSTRAINT uk_student_student_id UNIQUE (student_id)            -- enforces "create student fails if it already exists"
);

-- Join table for the many-to-many lecturer<->student assignment.
-- One row per assignment.
CREATE TABLE assignment
(
    lecturer_id BIGINT NOT NULL,           -- FK -> lecturer.id (surrogate, not the business id)
    student_id  BIGINT NOT NULL,           -- FK -> student.id (surrogate, not the business id)
    PRIMARY KEY (lecturer_id, student_id), -- composite PK prevents duplicate assignments
    CONSTRAINT fk_assignment_lecturer FOREIGN KEY (lecturer_id) REFERENCES lecturer (id),
    CONSTRAINT fk_assignment_student FOREIGN KEY (student_id) REFERENCES student (id)
);